### ISSUE TITLE
Spanish Translations not showing

### ISSUE THREAD

**Issue by carlosrovira** [stephenharris/Event-Organiser#235]
Hi,

I buyed event-organiser-pro and I'm using right now the following plugins:

Event Organiser 2.10.0
Event Organiser Pro 1.9.4
Event Organiser CSV 0.2.0

I see the spanish translations files in languages folder (the ones with "es_ES" suffixes)

But I can't see the translations working. For example:

* In the Main Left Menu I see "Event" instead of "Eventos"
* Inside there's "All Event" instead "Todos los Eventos"
* "Add New" instead "Añadir Nuevo" or "Adicionar Nuevo" or "Añadir Evento"

I'm checking the translation files with poEdit and searching for "Add New" I can see it translated to "Adicionar Nuevo", but the plugin is not using it.

Please I need some support since I buyed this plugin to use it for a client, and I can't show this in english, so is really important to get this solved as soon as possible.

Hope you can let me know what is happening.

Thanks in advance for your support.

Carlos

**Comment by stephenharris** [comment]
Hi @carlosrovira - sorry for the delay in getting back to you. As a Pro customer I strongly recommend you use the [Pro forums](http://wp-event-organiser.com/forums/forum/general-question/) as you're more likely to get prompt support there. 

I've just checked out 2.10 with the Spanish copy and I'm seeing some of these translated (Specifically in your first post). Below is a list of strings you reference above that are not translated into Spanish (as far as I can tell).

**Event Organiser**
 - [ ] Venue:
 - [ ] Show dates

Of these "Venue:" has no Spanish translation. "Show dates" does ("Mostrar fechas") but was marked as fuzzy (for some reason..., that will be fixed in the next update)

**Event Organiser Pro**
 - [ ] If you edit the event's dates you will need to update any event tickets. If you remove a date, any bookings for that date will be ignored until you re-assign them an event date.
 - [ ] Add Ticket
 - [ ] Do not cap

Of these the first two don't have translations and the last was not translatable (this shall be fixed in the next update).

All translations are community supplied - there's an online editor available for submitting translations. (Spanish is currently at 99% for the free version), details of which can be found here: [docs.wp-event-organiser.com/i18n/](http://docs.wp-event-organiser.com/i18n/).

Feel free to report any further strings not being translated here.

**Comment by stephenharris** [comment]
A bug with the translating software meant some of these translations were present but marked as 'fuzzy'. For the free version this should be fixed in 2.13.0.

For Pro this will be fixed in 1.10.0. Spanish translation for Pro is currently at 97% for 1.10.0

**Comment by carlosrovira** [comment]
Great Stephen, the problem still isn't fixed in my installation, so hope there's a release soon.
(any dates to share?)

Thanks!

**Comment by stephenharris** [comment]
2.13.0 probably next week, Pro 1.10.0 a week or two after that (it's currently in [beta](http://wp-event-organiser.com/blog/announcements/event-organiser-pro-1-10-0-beta-2/)).

**Comment by stephenharris** [comment]
Closing this with release of 2.13.0. Pro 1.10.0 will be released shortly.
