### ISSUE TITLE
Plugin features inquiry

### ISSUE THREAD

**Issue by reojavier439** [stephenharris/Event-Organiser#261]
Hello,

I would like to inquire if the following tasks and features are present on this plugin or any of its related versions:

A. The events management system must be able to send payment reminders automatically.
B. The events management system must be able to cancel unpaid registrations automatically.
C. Create unique single use coupons.
D. Export updated list of participants.

Thank you and kind regards.

**Comment by stephenharris** [comment]
Hi,

A) The plug-in doesn't provide for payment reminders, this would require a cron job (implemented at the server, rather than application level, for any reliable service). I've worked with clients to do this (including e-mail and SMS alerts), but it is not a 'feature' in Pro.

B) There's no clean-up of unpaid bookings. These are left as 'pending' until payment is confirmed. The plug-in allows you to configure whether 'pending' bookings reserve spaces, so such unpaid bookings need not prevent other bookings.

C) There is a [discount codes extension](wp-event-organiser.com/extensions/event-organiser-discount-codes) that would allow this. You can set a limit on the number of times a discount code is used.

D) You can export bookings / tickets sold (a booking can contain multiple ticktets) to CSV. 

Hope that helps!

**Comment by cliffordp** [comment]
Bad link. Here's the right one: http://wp-event-organiser.com/extensions/event-organiser-discount-codes/
