### ISSUE TITLE
User submitted Event Reviews

### ISSUE THREAD

**Issue by mncomunityplanner** [stephenharris/Event-Organiser#269]
Hi, I wasn't sure how to post on the forum so I'm sorry if this is the wrong place.  I am wondering if anyone has used a review plug in or something like that with event organiser to review events.  I would like a five star rating field or something like that, with a review field that works similar to comments, so they show up on the event pages, and if it is a recurring event that they show up on the recurring pages.  I also want them to be able to submit pictures.  A bonus would be if they can also tag within the review, or choose from existing tags and the administrator can update the actual tags if needed.

I know it's a lot to ask, if there is something you think might work I can look at it and adjust if need be, although my php knowledge is low.  Thank you!

**Comment by stephenharris** [comment]
This plug-in was originally conceived as means of creating a [Edinburgh Fringe](http://en.wikipedia.org/wiki/Edinburgh_Festival_Fringe) review site. Though I've not had the time to implement that, my plan would have been to use a review plug-in which either worked with custom post types ('event') or could be edited to do so.

In this context, reviews would be for the event, regardless of which *date* was attended (after all, if the same event is happening on different dates which date the reviewer attended is of not much consequence). In part, this is why recurring events have just one page, not one page per date.

When I was toying with this idea it involved using https://wordpress.org/plugins/wp-postratings/ but I think it fell short of the functionality I wanted (a review + rating), something which it seems is offered by https://wordpress.org/plugins/comment-rating-field-plugin/ - but I've not looked at that plug-in so can't offer an opinion on it.

I'm sure there are also plug-ins out there that allow users to submit a picture with a coment to.

**Comment by cliffordp** [comment]
If 'event-venue' was a post type instead of a taxonomy, you could have ratings per single/recurring event AND per venue.

For example:
- gallery opening May 14 was 5 stars
- Hilton Hotel it was hosted at was 3 stars

Over time, the Hilton Hotel venue single-venue.php (or whatever) would have ratings and then get an average of 4.2 stars.

When someone creates a new event, they could pick from the top-rated venues or pick alpha-order or nearest their current location, etc.

**Comment by stephenharris** [comment]
That's true, but it would not be possible to convert venues from a taxonomy to a post type and maintain backwards compatibility (at least, not easily). (There are also reasons why I chose to go with taxonomy over post type). It would still be possible to add ratings to venues, but I'm just not sure there is an existing plug-in that adds ratings to taxonomy terms (maybe this one: https://wordpress.org/plugins/multi-rating/ ?).

**Comment by cliffordp** [comment]
Any insight why taxonomy vs connected post type for Venues? Always been curious why this and other events plugins do it this way.

**Comment by stephenharris** [comment]
Taxonomies are intended to group post items - so it's a natural choice when wishing to group events (i.e. events at this venue). Queries relating to events at venues builds upon (rather than alongside) WordPress' API - which means less code is required. It's also more efficient than using post meta to store a reference to a venue (although if I were to use post types for venues, I'd using a table similar to posts2posts).

On the flip side, taxonomies in WordPress aren't much of an 'object' in their own right. They have a description, and that is all. No custom fields (*yet...*), and a minimal admin page. Because of this the admin page has to build in parallel rather than on top of that, and because of this some plug-ins that you might like to use for venues probably don't work.

The decision to go with the former was that a better underlying architecture would be better in the long run than UX compatibility with other plug-ins. Also making taxonomy terms more like objects in their own right is on the roadmap for WordPress core. Lastly a post type UI for venues seemed pretty poor.

**Comment by cliffordp** [comment]
Makes sense. Thanks for the detailed explanation. My use case is a bit different then I guess. I essentially want the venues to NOT be re-used, since they / their information expires with the event (e.g. open houses).
