### ISSUE TITLE
Setting the WP timezone to a UTC-offset can result in irregularities

### ISSUE THREAD

**Issue by r-a-y** [stephenharris/Event-Organiser#287]
On a WP site, if you set the WP timezone to a UTC offset, EO automatically converts this to the first-matching city-specific timezone in `eo_get_blog_timezone()`.

So if you set the timezone to `UTC-4`, EO will set the timezone to `America/Porto Acre`.  This can lead to irregularities since at the moment, `America/Porto Acre` is actually using `UTC-5`.

This occurs when `DATETIMEOBJ` is passed to `eo_format_datetime()`.

Since this is a weird bug to experience and is not really a coding issue, I would recommend updating the documentation so sites are advised to set a specific tz timezone for their WP timezone:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by stephenharris** [comment]
This is actually being addressed in 3.0.0. (See [this branch](https://github.com/stephenharris/Event-Organiser/tree/timezone) ([canonical url](https://github.com/stephenharris/Event-Organiser/tree/e65f74d51163166010eca6368dd22ab22fa29b26)), which is already merged into develop). Specifically, see this commit: https://github.com/stephenharris/Event-Organiser/commit/70b99b1216504c98f09f480e729ef911864bcc56

Rather than a guess a timezone from an offset - which was giving some really odd results sometimes, and just wrong results the rest, it will use the Etc/GMT timezones instead. These are [deprecated](http://php.net/manual/en/timezones.others.php) but I think they represent a better option than the current behaviour. A (dismissable) admin notice will appear for sites using a non-zero offset from UTC advising them to choose a city instead. 

Unfortunately, not all offsets supported by WordPress are supported by DateTimeZone. In that case it defaults to UTC. However, unless daylight savings are involved or importing/exporting events from/to other timezones this is unlikely to cause any problems. The plug-in stores 'floating' dates - events aren't tied to a particular timezone, they're assumed to be in the site's timezone.

**Comment by r-a-y** [comment]
Cool, thanks for addressing this in v3.0.

Sounds like this will work just fine.  Going to close this! :)
