### ISSUE TITLE
iCal feed produces incorrect time with DST

### ISSUE THREAD

**Issue by stephenharris** [stephenharris/Event-Organiser#293]
Steps to reproduce:
 - Set site timezone to a city which observes DST
 - Create a recurring event, part-day event whose occurrences span over a DST boundary
 - Import feed into a calendar application

Observe that the event's time changes as it crosses the DST boundary.

This bug exists because Event Organiser converts all datetimes to UTC in the feed. For one off events, or events recurring within the same DST 'period' this is fine. But as shown above this can cause issues.

The fix would be to include the timezone with the datetime values (patch to follow). However, this could cause a new problem: what if the receiving calendar application doesn't understand the timezone as specified? This could cause all events to appear 'off'.

**Comment by bluec** [comment]
Hi Stephen, I came across this problem too [1] and was just beginning to investigate this issue myself but you're already quite a few steps ahead. A quick look at the patch and it seems good to me - I'd love to see this implemented.

If a client application didn't understand the timezone specificed surely that would be a broken client implementation and not the fault of this plugin? To me that would be less bad than the current situation where the generated ICS file is "broken".

Could your concern be easily overcome by a "Make ICS export timezone aware?" option within the plugin settings? Turn it off and it acts as it does now, and turn it on and it "fixes" this bug?

[1] Support thread: https://wordpress.org/support/topic/incorrect-ics-feeds-due-to-daylight-savings-time

**Comment by stephenharris** [comment]
> If a client application didn't understand the timezone specificed surely that would be a broken client implementation and not the fault of this plugin?

Yes, but users don't always see that way ;). The principle at play here is 'do no harm' - if an existing user has been using the plug-in for years without any issues and suddenly an update to this plug-in breaks their site's feed, they're going to pin the blame on the plug-in. 

That said, if you take a look a lot of calendar applications, they do use fairly standard timezone identifiers, - and if we look in particular the most popular calendar applications (Google calendar, iCalendar) then we can probably be reasonably sure only a small contingent would be affected. So I'm definitely leaning towards implementing this patch (possibly 3.0.0).

As noted in the thread you linked to, (I think our replies are passing each other), you can implement this fix yourself in a 'future proof' way.

**Comment by bluec** [comment]
Yep I understand the unwillingness to break things!

I am not hugely familiar with the ICS specs but my understanding is that the timezone identifiers used can be defined within the ICS file using the VTIMEZONE component, such as this:

```
BEGIN:VTIMEZONE
TZID:Europe/London
X-LIC-LOCATION:Europe/London
BEGIN:DAYLIGHT
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
TZNAME:BST
DTSTART:19700329T010000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
TZNAME:GMT
DTSTART:19701025T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
```

This would theoretically overcome any problem of a client application not being aware of the declared timezone (again, assuming the client isn't broken!). It could be a pain to implement though because there are tons of timezones with lots of definitions but perhaps there is a PHP library that already takes care of this.

Just an idea, or perhaps adding the functionality but keeping it "off" by default may be the best bet?

**Comment by bluec** [comment]
Meant to reference this: http://www.kanzaki.com/docs/ical/vtimezone.html

**Comment by stephenharris** [comment]
Including a VTIMEZONE definition is definitely the best route, but this a fairly non-trivial task (so I thought).

However since then I've discovered: http://stackoverflow.com/a/25971680/932391 (also for reference http://php.net/manual/en/datetimezone.gettransitions.php).

There are still some issues to be ironed out, e.g. php5.2 compatability and performance testing, but this could be a go-er.

**Comment by stephenharris** [comment]
I don't think php5.2 compatibility is going to be feasible, but nor do I think it is required given that this a very edge case, that *might* happen with some calendar applications, when used on server with EOL PHP version (since Jan 2011), with non-catastrophic consequences. 

Should anyone fall foul of the above, then can simply copy the old `ical.php` template into their theme and the problem is immediately resolved.

Solution: define VTIMEZONE for required period for blog timezone if on PHP 5.3+, otherwise leave the timezone ID undefined and to be interpreted by the calendar application. This will obviously all need tests too.

**Comment by bluec** [comment]
Yes I found the same stack overflow answer and it looks good, although it does rely on an external library and I'm not sure how this suits your development or any licensing issues (https://packagist.org/packages/sabre/vobject).

With regard breaking things in legacy PHP versions or for (broken) clients that don't properly support timezones then I still believe it would be better to have a bool to just switch the whole functionality off and revert to everything being UTC, rather than rely on outdated versions of ical.php in theme folders.

**Comment by stephenharris** [comment]
My suggestion was simply to use the php function rather than the library - so there's no dependency / license issues to worry about.
