### ISSUE TITLE
eventorganiser-jquery-ui-style in conflict with the Divi theme

### ISSUE THREAD

**Issue by soderlind** [stephenharris/Event-Organiser#339]
Using the Pagebuilder in Divi, it is not possible to insert an image from the media manager (images aren't selectable). If I remove [eventorganiser-jquery-ui-style](https://github.com/stephenharris/Event-Organiser/blob/develop/includes/event-organiser-register.php#L154) from the DOM (using chrome inspect), I can select and insert images.

I'm running:
* WordPress 4.4.2
* [Divi 2.6.2](http://www.elegantthemes.com/gallery/divi/) 
* Event Organiser 3.0.2
* Event Organiser Pro 1.14
* Event Organiser Booking Notification Settings 1.0.0

What will I break if I deregister eventorganiser-jquery-ui-style ?

**Comment by stephenharris** [comment]
Hi @soderlind 

This is a bug with the Divi theme. They have been told multiple times by their own customers since at least one year ago. I've dug up this e-mail I sent to a mutual customer (dated February 2015):

> The theme's pagebuilder is loading it's own (old) copy of jQuery UI
> (et-pagebuilder/jquery-ui-1.10.4.custom.min.js) rather than using the
> WordPress' bundled scripts. I haven't pinpointed the exact problem, but
> ultimately it's the fact that two different versions of jQuery UI are
> loaded: ET's version and WordPress' version that EO Pro uses jQuery UI
> for the shortcode tinyMCE button.

and the customer's response after getting in touch with Elegant Themes:

> They told us to swap out the custom jQuery file used in the theme with the current version.  We renamed the current one to a temp name, and uploaded the most recent with their same file name.  Everything is working now.

I can't be certain that the bug is the same - but the symptoms are identical. 

To answer your question: if you remove it from that particular page, probably not much since Divi is presumably also loading a jQuery UI stylesheet. Removing it from other pages may affect functionality. I'd recommend following the advice given by Elegant Themes above, but also contact them to ask them to resolve the issue in an update.

**Comment by soderlind** [comment]
In the later releases Divi has fixed (most of?) the issues you mention above. 

The problem happens when `ui-state-disabled` is added to a class (and it's added to a lot of the classes on new-post.php). Searching through all my plugins and themes, the only plugin adding ui-state-disabled is yours and it happens in:

event-organiser/js/admin-calendar.js
event-organiser/js/event.js
event-organiser/js/jquery-ui-eo-timepicker.js
event-organiser/js/qtip2.js
event-organiser/js/time-picker.js
event-organiser-pro/admin/js/event-pro.js
event-organiser-pro/js/occurrence-picker.js

**Comment by stephenharris** [comment]
Have they?  They never replied to my e-mail, and certainly numerous customers have had this problem since that original report (though I can't remember when the last one was).

You never said, but I suspect the conflict is between Pro and Divi. Of the two scripts, only `admin/js/event-pro.js` should be running on that page. That script does indeed use `ui-state-disabled`: it uses is as part of a widget which builds on jQuery's datepicker, and returns it in a callback for it to be applied to the date cell. The actual application of that class is therefore done by jQuery datepicker, and there is nothing in that script which - in itself - could apply it to other elements.

If there were a bug in jQuery's datepicker or how Pro uses it, then I would expect to see this issue on a fresh install. Since I don't, and reports of this kind seem specific to the theme, then that suggests the theme is somehow involved. The only feasible explanation is that the theme is loading an older version of jQuery datepicker, over-riding the default one shipped with WordPress' jQuery copy. This _was_ what was happening before and the response the original reporter got did not suggest that this was something they were intending to fix - so I suspect that this is still the case now.

If you'd like me to take a look at your version of Divi just get in touch via: http://wp-event-organiser.com/contact

**Comment by soderlind** [comment]
My bad, you're correct. I added the following to my child theme functions.php and it looks it fixes the problem:

```php
function load_divi_fix() {
	global $wp_scripts;
	wp_enqueue_script( 'jquery-ui-core' );

	// get registered script object for jquery-ui
	$ui = $wp_scripts->query( 'jquery-ui-core' );

	// dequeue old script and style loaded by the Divi theme
	wp_dequeue_style( 'et_pb_admin_date_css' );
	wp_deregister_script( 'et_pb_admin_date_js' ); // loades jquery.ui.core.js, jquery.ui.widget.js, jquery.ui.mouse.js, jquery.ui.datepicker.js, jquery.ui.slider.js

	// load wp native scripts
	wp_enqueue_script( 'jquery-ui-widget' );
	wp_enqueue_script( 'jquery-ui-mouse' );
	wp_enqueue_script( 'jquery-ui-datepicker' );
	wp_enqueue_script( 'jquery-ui-slider' );

	// load a jquery ui theme matching current jquery ui version
	$protocol = is_ssl() ? 'https' : 'http';
	$url = "$protocol://ajax.googleapis.com/ajax/libs/jqueryui/{$ui->ver}/themes/smoothness/jquery-ui.min.css";
	wp_enqueue_style( 'jquery-ui-smoothness', $url, false, null );
}

add_action( 'admin_enqueue_scripts', 'load_divi_fix', 99 );

```

**Comment by stephenharris** [comment]
Thanks @soderlind for coming back to update this thread and posting this fix. I only hope that Elegant Themes decide to fix their theme.
