### ISSUE TITLE
Date range is displayed incorrectly when start and end dates are on same day of the month

### ISSUE THREAD

**Issue by dboulet** [stephenharris/Event-Organiser#359]
I have an event which begins on April 9th, and ends on May 9th. I output the date in my theme using this code:

```php
eo_format_event_occurrence( FALSE, FALSE, 'l, F j, Y', '', '&ndash;', FALSE );
```

The date is displayed like this:

**Saturday, April–Monday, May 9, 2016**

It should be:

**Saturday, April 9–Monday, May 9, 2016**

The day in the start date is missing.

**Comment by stephenharris** [comment]
The date formatting is a bit naive here. It starts from both ends and finds where the dates first differ (in the rendered format). To illustrate this, if 9th May 2016 was in fact a Saturday, it would look like:

**Saturday, April-May 9, 2016**

So it splits the dates where they first differ going from left-to-right and right-to-left.

The bug here is that '9' here is the same for start and end date but they don't actually refer to the same 9th. I think there needs to some added logic here to the effect:

 - If the year differs, don't group year/month/day tokens
 - If the month differs, don't group month/day tokens
 - If the date differs, don't group day tokens

**Comment by dboulet** [comment]
Thanks for your work on this, @stephenharris!
