### ISSUE TITLE
Fatal error: Call to a member function format() on boolean

### ISSUE THREAD

**Issue by dboulet** [stephenharris/Event-Organiser#360]
I’m seeing this error:

 `Fatal error: Call to a member function format() on boolean in /wp-content/plugins/event-organiser/includes/event-organiser-utility-functions.php on line 36`

I think that I’ve tracked this to an error in `eo_get_the_occurrence()`. I’ll file a pull request.

**Comment by stephenharris** [comment]
Is there any context for this error? I.e. is the function being invoked by some custom code or is there a particular page/action that triggers the error?

**Comment by dboulet** [comment]
I registered a custom taxonomy for events, and was seeing this error on the taxonomy term archive pages. I’m guessing that because this page is not native to Event Organiser, the events are not loaded properly, and sometimes have their occurrence ID missing.

This is the code I’m using to display the event date, in the loop:

```php
$date_format = 'l, F j, Y';
$time_format = 'g:ia';
eo_format_event_occurrence( FALSE, FALSE, $date_format, $time_format, '&ndash;' );
```

I noticed that if I instead load the events on the page using `eo_get_events()`, the errors disappear.

**Comment by stephenharris** [comment]
That would make sense. When an event/occurrence ID is not specified it uses the `$post->occurrence_id` property. (This is an alias for the 'event_id' column which actually refers to the occurrence ID). This is added as a result of the join between the posts table and events table.

Since there is no join, that value is 0, it's not finding the occurrence. There's no sanity checking here, hence the fatal error.

So the root cause is that why the plug-in applying the join for that custom taxonomy, although it is registered for events. 

The plug-in uses [this function](https://github.com/stephenharris/Event-Organiser/blob/b92ffe96e8b33fdf4c30fb2d651f546ac8664cd2/includes/event-organiser-archives.php#L350-L423) for determining if a query is 'for events'. That includes supporting custom taxonomies - but only if the only post type for that taxonomy is 'event'. (The reasoning here is that if there were other post types, they would not be included because of the JOIN).

Is 'event' the only registered post type for your custom taxonomy?

**Comment by stephenharris** [comment]
Incidentally, there is a filter to tell the plug-in whether a query is for events (http://codex.wp-event-organiser.com/function-eventorganiser_is_event_query.html) - but if there's a bug in the implementation, it would be nice to fix it ;)

**Comment by dboulet** [comment]
Thank you, @stephenharris. That explains it, in my case the custom taxonomy is used for more than just events, and the term archive page displays events mixed in with other post types.

For now, I’m displaying the events using `eo_get_events()` instead, and this fixes the error.

Maybe what is needed here is just a fix for the fatal error, perhaps a check in the function to make sure that `$datetime` is in fact an object and not `FALSE`. Events still wouldn’t be displayed properly, but at least code execution would not be halted.

**Comment by stephenharris** [comment]
@dboulet  just to get back to you on this. I don't want to abort silently as this masks the issue and hampers debugging.

Instead I think I will introduce an exception. This allows a developer to catch the exception and handle it however they like. If not caught, it would throw a fatal error, as we have now, but would at least provide some context (e.g. a more detailed error message, and prossibly a trace).
