### ISSUE TITLE
"Start time must be earlier..." check should be skipped for all day events

### ISSUE THREAD

**Issue by boonebgorges** [stephenharris/Event-Organiser#420]
Minor, but reported by a user: If you set start time later than end time and submit, the client-side validation (correctly) gives you an error. If you then check 'All Day', you still see the message. I'd suggest that the 'All Day' check should allow the time-based validation to be skipped.

**Comment by stephenharris** [comment]
Hi @boonebgorges  - sorry, had missed this ticket. Could you give a step-by-step guide to replicating this because I can't seem to replicate it. Additionally, I don't think there is any client side checking of the start and end dateime - it's all done server-side. On the wp-admin/post.php for events I selected a start time after the end time, and then selected 'All Day', and it was able to create the event.

**Comment by boonebgorges** [comment]
@stephenharris - On further digging, it looks like this may be a piece of custom interface that we introduced in bp-event-organiser. There is still some weirdness that takes place when you do manage to submit an item with a start date that preceds and end date, but this is likely also our fault.

Many apologies for the goose chase.
