### ISSUE TITLE
Event archive posts ordered from newest to oldest

### ISSUE THREAD

**Issue by JonathanBesomi** [stephenharris/Event-Organiser#422]
Hi community:octocat:,

I would like to suggest a new feature.

Add a "In event archive order posts from newest to oldest" checkbox in settings.
There is more chance that an user is looking for a new post instead of an old one. For example I need this enhancement in my website right now.

Let me know what do you think. If you appreciate the idea I can try to do a fork.

**Comment by stephenharris** [comment]
I'm not sure I see much need for this setting. Typically when listing event dates you'll want it chronological order which is "oldest" to "newest", although you wouldn't typically use that term since generally the dates tend to be in the future ("earlier" to "later" perhaps is more accurate). That's the default ordering of events.

Usually when the reverse ordering is requested it is because people do not want to see past events (the oldest), at the top. The solution here is to only show future events. There is an option for this on the settings page and various shortcodes and widgets etc will have their own options.

**Comment by JonathanBesomi** [comment]
Thank you for your feedback and your exhaustive arguments. The community was not active on this post so I guess that was not so important. I consider this issue closed. Best regards
