### ISSUE TITLE
Default Time Format Changed

### ISSUE THREAD

**Issue by pronetsweb** [stephenharris/Event-Organiser#424]
Hi, it seems since a recent update that the default time format on shortcode templates has changed.

There are two parts to this issue:
- First is that in the past I've setup templates where the time format was in the "date format" argument as a shortcut, for example: %end{g:i:a}%. This now causes duplication since there is a default time format, so for a 10pm event this shows: 10:00:pm 10:00 pm. As if we put: %end{g:i:a}{g:i a}%
- Similar issue where we've specified a date format but not a time format, now causes a change in how display happens unless we go back and add an empty argument: 
%start{n-d}% displays as "11-08 7:00 pm" now unless we change to: %start{n-d}{}%

Not sure if this was an intentional change or a regression but it is inconvenient to some extent as the behavior of this shortcode and templates is a bit fuzzy (would be nice if it supported just having the entire date/time format in one argument).

**Comment by stephenharris** [comment]
Hi @pronetsweb - the change was intentional, but I think neglected to appreciate that users would be using the tag in the way you have described. Having made the change now, I'm reluctant to revert it again.

As you have noted, to get just the date or time:

    %start{g:ia}{}%

The purpose of the second argument is that it is only used if the event is a non-all day event. This allows you to use specify datetime formats for both all-day and non-all-day events.
