### ISSUE TITLE
Event List empty

### ISSUE THREAD

**Issue by olesq** [stephenharris/Event-Organiser#432]
Event List showing as empty for editing purposes although all events displaying as normal in calendar etc. Total of events showing correctly at top of page. Seems to have happened since 'group by' fix.
[WP-eventlist.docx](https://github.com/stephenharris/Event-Organiser/files/1806280/WP-eventlist.docx)

**Comment by stephenharris** [comment]
Hi @olesq would you be able to install the Query Monitor plugin ( https://en-gb.wordpress.org/plugins/query-monitor/) and leave a comment here with the main SQL query for events (involving eo_events table)?

I've not been able to replicate this issue, so I'm wondering if its down to a MySQL version, plugin configuration or a conflict with another plugin.

**Comment by olesq** [comment]
Hi Stephen

Added Query Monitor Plugin as requested and when I then tried to list
events it immediately flagged up a database query error which refers to
eo_events table. I have attached a screen print of this. if you need more
output from Query Monitor please let me know what you need - I have not
used it before.

Thanks

Olly

**Comment by stephenharris** [comment]
@olesq I don't think attachments work when replying by email. You can upload the image by visiting this issue in a web browser.

**Comment by olesq** [comment]
Here is screen print of output from Query Monitor
[WP-eventlist-QM-eo-events-join.docx](https://github.com/stephenharris/Event-Organiser/files/1810940/WP-eventlist-QM-eo-events-join.docx)

**Comment by stephenharris** [comment]
Thanks @olesq - that's helped a lot in getting to the bottom of this. The fix for #430 was to join the table against itself which results in a (potential) `N^2` join where `N` is the number of rows in the `eo_events` table. If you have enough rows that is set larger than you SQL server's `MAX_JOIN_SIZE` then you'll get this error.

The solution is two fold - first, the plug-in will explicitly tell the MySQL server that 'big joins are ok' (`SET SQL_BIG_SELECTS=1;`). It will then ignore the `MAX_JOIN_SIZE` limit, and fix the immediate issue.

The `MAX_JOIN_SIZE` is there to prevent applications from crashing because they run a join too large for the mysql server to handle. Therefore, the second change is that the admin event list page will run a different query when grouping the event dates; a more efficient one, which is possible because it doesn't matter how it groups the dates.

Therefore, out of the box the plug-in won't run the (potentially) large JOIN query, and will do only when 'grouping occurrences' in the settings page, or shortcode/widget settings - is enabled. 

There'll be an update in the next few days - if you are able to test fix ahead of that release, I would be very grateful.

**Comment by olesq** [comment]
Hi Stephen

Happy to help testing if I can - not sure how I can do this ahead of your
release?

Olly

**Comment by olesq** [comment]
Hi Stephen

Just wondering if fix will available soon - or have you hit some problems?

Thanks

Olly

**Comment by stephenharris** [comment]
HI @olesq sorry for the delay - that should be released now.
