### ISSUE TITLE
How to remove map from specific venues

### ISSUE THREAD

**Issue by colingaj** [stephenharris/Event-Organiser#440]
Hi

I would be grateful if you can direct me to the specific PHP files that would allow me to remove the map display from events with a specific venue. The issue is that in some locations the addresses are people's homes that my client does not want displayed. In these instances, I don't input a street address but just a city, with the result that Google maps shows the middle of the city which is misleading information, hence my request.

Thanks
Colin

**Comment by stephenharris** [comment]
Hi Colin,

The line that renders the venue on the event page can be found here: https://github.com/stephenharris/Event-Organiser/blob/develop/templates/event-meta-event-single.php#L108

It also appears on the venue page: https://github.com/stephenharris/Event-Organiser/blob/develop/templates/taxonomy-event-venue.php#L42

You can copy both files into your theme and edit them there. The plug-in will use those templates rather than the ones int he plug-in.

**Comment by colingaj** [comment]
Sweet! Works like a charm. Thank you so much!
