### ISSUE TITLE
Eventlist-Placeholder Values are empty ... 

### ISSUE THREAD

**Issue by Webdeern** [stephenharris/Event-Organiser#445]
Hello! 
I use Event-Organiser, Elementor and OceanWP Theme,
I added a shortcode to a OceanWP-footer-template:

`"%start{d.m.Y}{}%, %start{H:i}{}% - %end{H:i}{}% Uhr: <a href="%event_url%">%event_title%</a>"`

this works on most pages at the website, see here: 
https://www.stricktiger.de/ ) (Startpage) or
https://www.stricktiger.de/neu-und-interessant/  (Blog-page)

but the start- and end-values are empty on blog-pages in category-view:

see here: https://www.stricktiger.de/category/angebote/

I am sure it is a conflict of variable names / placeholder names %end% and %start% and I learned in school not to use such common names to avoid conflicts
Here I have the conflict and I do not know how to solve this

Help me out please!  I asked for help in the wordpress.plugin-support but no answer there for 5 days and 18 hours now and I MUST fix this situation ;=(

Connie

**Comment by stephenharris** [comment]
Hi Connie,

It's very unlikely to be a conflict of names - the placeholders are used in context in which only Event Organiser would be parsing.

I'm afraid I don't know what's causing the dates not to appear on that page, and for it to appear on the others. The code for outputting the dates is here: https://github.com/stephenharris/Event-Organiser/blob/develop/classes/class-eventorganiser-shortcodes.php#L325-L352 so that is probably the best place to start debugging.
