### ISSUE TITLE
error on event booking 

### ISSUE THREAD

**Issue by Ziabelle77** [stephenharris/Event-Organiser#462]
Hello, 
I have been using Event organiser and it worked fine (I have the Pro version + Venue Markers + Stripe Gateway) but now I have an error showing ! 
When a user tries to book an event, after hitting the submit button, I have an error PHP (see screenshot attached) 
The booking is OK (e-mail are sent to user and to admin) but the next screen is showing the error. 
Thanks a lot for help 
Isabelle 
<img width="1666" alt="Capture d’écran 2019-05-21 à 13 59 39" src="https://user-images.githubusercontent.com/50877327/58105267-7e1c7700-7be6-11e9-8801-764260837784.png">

**Comment by Ziabelle77** [comment]
Up 

Can somebody help me with this ? The plugin becomes unusable this bug shows up everytime someone makes a booking ... 

Thanks in advance.

**Comment by stephenharris** [comment]
Hi @Ziabelle77 - sorry you haven't had a reply. As a pro customer I'd encourage you to use the support [forums](https://groups.google.com/a/wp-event-organiser.com/forum/#!forum/support) as your more likely to get a quicker reply.

I've looked into this, and it's the result of a conflict with a third-party plugin. In particular, the plug-in uses `$_POST['name']` to store an array (first and last name of the bookee). It would appear that another plug-is using that value to query posts of that name, e.g. 

     get_posts( array('name' => $_POST['name']) );

However, that function expects the value be a string (name of a post), which is why you're getting this warning.

The fix is really in the plug-in/theme that's doing this, since it shouldn't be executing that query. But if you can determine which plug-in/theme it is then I can take a look and try and suggest a fix for this.

**Comment by Ziabelle77** [comment]
Hi Stephen, 
Thanks for your answer. I couldn't find the way to get to the support forum, that's why I posted here. (and now I still can't access the google group on the link here above, I have a message saying I don't belong to the group...) 
But now the bug is gone (after I made some new updates theme and plugins) but I keep your advise in case it show up again.
